In [14]:

# SYNTAX ERROS
# When the code does not conforms to the rule of the language

for i in range(10):
    print(i)


# removing the : throws a syntax erros
# improper indentation will cause syntax error
# missing quotes will cause a syntax error

0
1
2
3
4
5
6
7
8
9


In [15]:
# LOGICAL ERROS
# Right code but wrong logic
# Doing something not intended
# e.g. subtracting instead of adding two numbers

def double_number(num):
    return num + num

double_number(4)
# Ideally, it should be multiply * instead of +

# RUN TIME ERROS
# OTHER DATA RELATED ERRORS

8

In [16]:
# RUNTIME ERROR
# errors that occur while the code is running
# code may be correct, syntax may be correct but something happened 
# e.g failed database connection
x = 2; y=0
print(x/y)
# failed bacuase nothing devides 0
# other examples are missing file, wrong file etc


ZeroDivisionError: division by zero

In [ ]:
# OTHER RELATED ERROR
# data type errors
# e.g
age = "twenty"
if(age > 20):
    print("Senior")

# error because data type in comparison is not supported

TypeError: '>' not supported between instances of 'str' and 'int'

In [ ]:
date_str = "2020-12-11"
year, date, month = map(int, date_str.split("-"))
print(f"Todays date is {year} {month} {date}")

Todays date is 2020 11 12


SQL Concepts

SQL - structured query language
Tables - a frame where data is stored
Views - combination of tables
Primary key - A unique identifier in a table
Foriengn Key - A primary key as a field in another table

Fact Table - Table which stores primary keys as foriengn keys and quantitative details i.e FACTS about an event, sales, or activities whic have been carried out by processes or people whose details are stored in the dimension tables.

Dimension Table - Stores descriptive or qualitative information of things or people with their primary keys whose quantitative activities or items are in the fact table e.g Name, address etc


SQL COMMANDS
DDL - Data Definition Langauages
    Used to define the database structure: Create, Drop, Alter, Truncate

DML - Data Manipulation Language
    Used to manage data in the database: Insert, update, delete

DCL - Data Control Language
    To manage access to a database: Grant, Revoke

DQL - Data Query Language
    To retrieve data from the database: Select


DATA TYPES IN SQL
Numeric: int, decimal or numeric (numbers with fixed precision), float or real (numbers where precision is not critical), 
            bigint, tinyint, bit (true or false usually, 0 0r 1)

String: Char (for fixed length characters e.g country code), Varchar (when the length of the char is not know, e.g Names),
        text (for longer legth texts, e.g comments, descriptions, essays etc), 
        Nchar and Nvarchar (similar to char and varchar but for Unicode characters e.g names from other languages such as texts with apostrohe's or alphabets with strokes or caps on them)

Date: Date (year, month and dat), time (hour:seconds), datetime (date and time), timestamp (current date and time), 
        year (year)


CONSTRAINS
Primary Keys - Unique identifies
Foreign Keys - Primary keys from another table
Not NULL - Ensures there's something in the field
NULL - Allows nothing in the field
UNIQUE - Ensures values in this field are all different
DEFAULT - Value to be saved when nothing is inserted in that field


DATA MODELLING
Normalisation: A way of organising data in a database to reduce redundancy and improve data integrity by dividing larger tables into smaller related tables

Redundancy: Occurance of repeated data unnencessarily 

First Normal Form (1NF): All columns would contain Atomic values, columns should contain one data type, each row will be unique i.e no repeition

Second Normal Form (2NF): The table would already be in 1NF, tables would be broken down into modular parts and be linked by primary and foriegn keys

Third Normal Form (3NF): Table would already be in 2NF, there should be no transitive dependencies, i.e columns that are non-keys should not depend on non-key columns


ENTITY RELATIONS DIAGRAM (ERD)
A diagram that shows the relationships between tables
Tools to draw ERDs include lucidchart, draw.io

LUCID CAHRT
Shapes to use on lucid chart
1. entity diagrams 2. cardinality (1-to-1, 1-to-many, many-to-1, many-to-many)

STAR SCHEMA
A schema where the fact table is in the middle and the dimension tables are spread out in a star-like format

SNOWFLAKE SCHEMA
A schema where the table is normalized even further such that some fields are modularised to have their own table so as to reduce redundancy i.e. where new tables are created to just serve as lookup tables
In this case, the star-schema is further exapanded such that the entities on the star edges have smaller entities linked by a primary and foriegn key





Databases are used to store structured, trsanctional data for real-time use purposes (day-to-day data processing)
They are normalized to reduce redundancy and increase efficiency and integrity

Datawarehouses are used to store large, historical, complex data in other to serve data for purposes such as machine learning models, data streaming, analysis etc

Databases
Databases are used for day-to-day operational use (OLTP – Online Transaction Processing).
- Designed for fast inserts, updates, and retrievals.
- Store current data in a normalized form to reduce redundancy.
- Used in applications like banking systems, CRMs, web apps.
Example in banking:
Tables like Customers, Accounts, Transactions, Loans are normalized.
Each transaction is logged in real time, searchable by account, etc.


Data Warehouses
Data warehouses are used for analytical and reporting purposes (OLAP – Online Analytical Processing).
- Optimized for reading and aggregating large volumes of data.
- Often use denormalized schemas like star or snowflake schema.
- Data is structured for data mining, ML, BI, trend analysis.


In a Database (OLTP) - Tables are normalized
In a Datawarehouse (OLAP) - Tables are denormalized and prepared either in star schema or modular shcema (where each domain like transactions and loans have their own schema with fact tables and dimension tables)




NUMPY - Numerical Python

A list is referred to as Array in Numpy
A one dimensional array is called a vector


In [2]:
import numpy as np

# converting a list to array
vec = [1,2,3,4]
type(vec)


list

In [3]:
vec = np.array(vec)
type(vec)

numpy.ndarray

In [4]:
# MATRICES
mat = np.array([[1,2,4], [1,4,5], [3,1,2]])
print(mat)
print(f"shape of the array {mat.shape}")

[[1 2 4]
 [1 4 5]
 [3 1 2]]
shape of the array (3, 3)


In [7]:
# ZEROS AND ONES ARRAY

print(np.zeros((2,3)))
print(np.ones((2,4)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
# SLICING IN MATRIX ARRAY
# to get a one dimensional array, the format of slicing is np.array[vertical index, horizontal indes]
# in multi dimensional array, np.array[vertical start:vertical end, horizontal start:horizontal end]

print(mat)

# get the first top left element
mat[0, 0]

# top row
mat[0, :]

# first column
mat[:, 0]

# first two rows, first two columns
mat[0:3, 0:2 ]


[[1 2 4]
 [1 4 5]
 [3 1 2]]


array([[1, 2],
       [1, 4],
       [3, 1]])

In [30]:
### Boolean array slicing (Conditional slicing)
# values greater than two
print(mat[mat>2])

# multiple conditions
print(mat[(mat<1) | (mat >3)])

[4 4 5 3]
[4 4 5]


In [47]:
# Modifying grid or matrices
# appending np.append(matrix, [[values]], row or column) where axis=0 is row, axis=1 is columns
# appending np.append(matrix, [[values]], row or column) where axis=0 is row, axis=1 is columns
print(mat)
mat_append_col = np.append(mat, [[4],[12],[1]], axis=1)
mat_append_row = np.append(mat, [[4,12,1]], axis=0)
print(mat_append_col)
print(mat_append_row)

[[1 2 4]
 [1 4 5]
 [3 1 2]]
[[ 1  2  4  4]
 [ 1  4  5 12]
 [ 3  1  2  1]]
[[ 1  2  4]
 [ 1  4  5]
 [ 3  1  2]
 [ 4 12  1]]


In [50]:
# removing rows
# np.delete(matrix, [row_or_column_index], axis)
mat
mat_rm_row = np.delete(mat, [2], axis=1)
mat_rm_row

array([[1, 2],
       [1, 4],
       [3, 1]])

In [69]:
# NUMPY METHODS
# arange, reshape, linspace, eye

mat_range = np.arange(0,50, 5)
mat_range

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [61]:
mat_range.shape
# reshape, changes the shape of the array
# to get a successful reshape, the specified shape when multiplied should be equal to the number of total items in the original array 
# e.g mat_r = 20 items, mat_reshape = 5*4 = 20

mat_r = np.arange(0,20)
mat_reshape = mat_r.reshape(5,4)
mat_reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [76]:
# linspace - creates array with an evenly spaced interval
mat_linspace = np.linspace(0,20, 5)
mat_linspace

array([ 0.,  5., 10., 15., 20.])

In [79]:
# eye, used to create an identity matrix
mat_eye = np.eye(4)
mat_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [94]:
# sum, max, min, etc
print(mat)
mat.sum(axis=1) # by row
# mat.sum(axis=0) # by column

# min of each column
mat.min(axis=0)
# index of min value in each column
mat.argmin(axis=0)

# min of each row
# mat.min(axis=1)



[[1 2 4]
 [1 4 5]
 [3 1 2]]


array([0, 2, 2], dtype=int64)

In [104]:
# Random, randn, randint, randn

mat_rand = np.random.rand(3,6)
mat_rand

# randn: creates array from a normal distribution 
mat_randn = np.random.randn(3,4)
mat_randn

# randint: creates array with integers
mat_randint = np.random.randint(1, 20, size=(4,4))
mat_randint

array([[ 8,  7,  2, 15],
       [ 4, 11,  9,  9],
       [15, 10, 16, 19],
       [ 1,  4, 13,  5]])

PANDAS - Panel Data

Is like the typical table with rows and columns
Used for
1. Data transformation
2. Advanced data filtering
3. Indexing and slicing
4. Merging and joining
5. Handling missing data
6. Data type conversions etc

In [105]:
import pandas as pd

In [107]:
# creating pandas series from a list
pd_list = [23,12,15, 34]
pd_series = pd.Series(pd_list, name='PD List')
print(pd_series)

0    23
1    12
2    15
3    34
Name: PD List, dtype: int64


In [109]:
# creating pandas series from a dictionary
pd_dict = {'a':30, 'b':45, 'c':39, 'd':22}
pd_ser_dict = pd.Series(pd_dict)
pd_ser_dict

a    30
b    45
c    39
d    22
dtype: int64

In [110]:
# pandas series from a numpy array
np_array = np.array([12,13,24,50,3])
pd_series_np_arr = pd.Series(np_array)
pd_series_np_arr

0    12
1    13
2    24
3    50
4     3
dtype: int32

In [119]:
# creating a data frame from a list
cu_columns = ['customerID', 'age', 'income']
cu_data = [['001', 24, 24000], ['003', 22, 30000]]
customer_df = pd.DataFrame(cu_data, columns = cu_columns)
customer_df

customerID  age  income
0        001   24   24000
1        003   22   30000

In [123]:
# creating data frame from dictionary
dict_data = {'customerID':[1001, 1002, 1003], 'age':[24,22, 26], 'income': [24000, 30000, 45000]}
dict_df = pd.DataFrame(dict_data)
print(dict_df)

   customerID  age  income
0        1001   24   24000
1        1002   22   30000
2        1003   26   45000


In [ ]:
## BASIC OPERATIONS IN PANDAS

# selecting a column
customer_df['age']

#selecting multiple columns
customer_df[['customerID', 'age']]

# adding a new columns
customer_df['savings'] = customer_df['income']*0.1
customer_df

# deleting a columns
del customer_df['savings']
customer_df

# wrting data frame to CSV file
customer_df.to_csv('customer_data.csv', index=False)

# reading a CSV file into a dataframe
# use r in pathname to ignore backward slash or alternatively manually change the backward slash to forward slashes
customer = pd.read_csv(r'C:\coding-trainings\10Alytics\Code/customer_data.csv')
customer

customerID  age  income
0           1   24   24000
1           3   22   30000

In [141]:
# filtering
income_df = customer_df[['age', 'income']]
income_df

# high income df
high_income = customer_df[customer_df['income'] > 25000]
high_income

customerID  age  income
1        003   22   30000

In [145]:
# performing basic aggregation
# sum
total_income = customer_df['income'].sum()
total_income

# mean
avg_age = customer_df['age'].mean()
avg_age

# max
max_age = customer_df['age'].max()
max_age

24

In [204]:
## Joins or merges
customer_df = customer_df
customer_df['customerID'] = [1001, 1002]
sales_data = {
    'customerID': [1001, 1002, 1003],
    'products':['fish', 'maggies', 'books'],
    'expenses': [2000, 1500, 3050]
}
sales_df = pd.DataFrame(sales_data)
print(sales_df)
print(customer_df)
# inner join
customer_inventory = pd.merge(customer_df, sales_df, on='customerID', how='outer');
customer_inventory

   customerID products  expenses
0        1001     fish      2000
1        1002  maggies      1500
2        1003    books      3050
   customerID  age  income
0        1001   24   24000
1        1002   22   30000


customerID   age   income products  expenses
0        1001  24.0  24000.0     fish      2000
1        1002  22.0  30000.0  maggies      1500
2        1003   NaN      NaN    books      3050

In [ ]:
## ADVANCED PANDAS TOPICS
# reading excel file
excel_df = pd.read_csv('customer_data.csv')

# handling missing values
# 1. Find out if there are missing values
#customer_inventory.info()

# METHOD 1
# 2. Remove the rows with missing values
clean_cust_inv = customer_inventory.dropna()
print(clean_cust_inv)

# METHOD 2
# Use advanced algorthims to fill in the missing values
# such as using mean or median values or by interpolation
fill_cust_inv = customer_inventory.fillna(customer_inventory['age'].mean())
print(fill_cust_inv)



   customerID   age   income products  expenses
0        1001  24.0  24000.0     fish      2000
1        1002  22.0  30000.0  maggies      1500
   customerID   age   income products  expenses
0        1001  24.0  24000.0     fish      2000
1        1002  22.0  30000.0  maggies      1500
2        1003  23.0     23.0    books      3050


In [200]:
# checking columns datatype
customer_inventory.info()

# converting types
fill_cust_inv['expenses'] = fill_cust_inv['expenses'].astype(int)
fill_cust_inv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   customerID  3 non-null      int64  
 1   age         2 non-null      float64
 2   income      2 non-null      float64
 3   products    3 non-null      object 
 4   expenses    3 non-null      int32  
dtypes: float64(2), int32(1), int64(1), object(1)
memory usage: 240.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   customerID  3 non-null      int64  
 1   age         3 non-null      float64
 2   income      3 non-null      float64
 3   products    3 non-null      object 
 4   expenses    3 non-null      int32  
dtypes: float64(2), int32(1), int64(1), object(1)
memory usage: 240.0+ bytes


In [221]:
# GROUPING AND AGGREGATING

# Adding rows to a dataframe
new_sales_data = pd.DataFrame([
    {'customerID':'1004', 'products':'fish', 'expenses': 1300},
    {'customerID':'1005', 'products':'maggies', 'expenses': 2000},
    {'customerID':'1006', 'products':'meat', 'expenses': 5000},
])

sales_df_2 = pd.concat([sales_df, new_sales_data], ignore_index=True)

# grouping by products
grouped_sales = sales_df_2.groupby('products').agg({'expenses':['sum','mean']})
grouped_sales


expenses        
              sum    mean
products                 
books        3050  3050.0
fish         3300  1650.0
maggies      3500  1750.0
meat         5000  5000.0

In [230]:
# handling duplicate values

# METHOD 1
# Drop duplicateed rows
dup_row = pd.DataFrame([{'customerID':'1006', 'products':'meat', 'expenses': 5000}])
sales_df_2 = pd.concat([sales_df_2, dup_row], ignore_index=True)
sales_df_2

sales_df_2 = sales_df_2.drop_duplicates(subset='customerID', keep='first')
sales_df_2

customerID products  expenses
0       1001     fish      2000
1       1002  maggies      1500
2       1003    books      3050
3       1004     fish      1300
4       1005  maggies      2000
5       1006     meat      5000

In [233]:
# SORTING DATA
sorted_df = sales_df_2.sort_values(by='expenses', ascending=False)
sorted_df

# RENAMING A COLUMNS
sorted_df = sorted_df.rename(columns={'expenses':'expense'})
sorted_df

customerID products  expense
5       1006     meat     5000
2       1003    books     3050
0       1001     fish     2000
4       1005  maggies     2000
1       1002  maggies     1500
3       1004     fish     1300

In [245]:
# CONDITIONAL SELECTIONS
cond_filt = sorted_df[(sorted_df['expense'] > 2000) & (sorted_df['expense'] < 5000)]
cond_filt


customerID products  expense
2       1003    books     3050

In [262]:
# INDEXING AND SLICING
# using .loc and .iloc mothods
# loc slices based on labels
sales_df_2
# label_sliced = sales_df_2.loc[0:2, 'products':'expenses']
# label_sliced

# .iloc slices based on index positions
iloc_sliced = sales_df_2.iloc[0:2, 1:3]
iloc_sliced

# slicing by index
# set the index
# sales_df_2.set_index('customerID', inplace=True)
sales_df_2

products  expenses
customerID                   
1001           fish      2000
1002        maggies      1500
1003          books      3050
1004           fish      1300
1005        maggies      2000
1006           meat      5000